FROM python:latest

# MySql / MariaDB Config
ENV MYSQL_USER "mysql_user"
ENV MYSQL_PASSWORD "mysql_password"
ENV MYSQL_HOST "mysql_host"
ENV MYSQL_PORT "3306"
ENV MYSQL_DATABASE ""
ENV MYSQL_PREFIX "_"

# LDAP Config
ENV LDAP_HOST "ldap_host"
ENV LDAP_PORT "389"
ENV LDAP_SSL "false"
ENV LDAP_TLS "false"

ENV LDAP_BINDDN ""
ENV LDAP_BINDPASS ""

ENV LDAP_FILTER ""
ENV LDAP_BASEDN ""
ENV LDAP_GROUPBASE ""
ENV LDAP_USERBASE ""
ENV LDAP_ ""